version: "3.7"
services:
  app:
    container_name: booking_app
    build: dentist_booking/
    volumes:
      - ./dentist_booking:/django
    ports:
      - 8000:8000
    image: app:django
    env_file:
      - docker_envs/django.env
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data:rw
    env_file:
      - docker_envs/postgres.env
    container_name: postgres_db

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis_data:/data:rwe
    container_name: redis

  celery:
    restart: always
    build:
      context: dentist_booking/
    command: celery -A dentist_booking worker -l DEBUG
    volumes:
      - ./dentist_booking:/django
    container_name: celery
    depends_on:
      - db
      - redis

volumes:
  pg_data: {}
  redis_data: {}