# Generated by Django 4.0.5 on 2022-06-25 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('required_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_appointments', to=settings.AUTH_USER_MODEL)),
                ('dentist', models.ForeignKey(limit_choices_to=models.Q(('groups__name', 'Doctors')), on_delete=django.db.models.deletion.CASCADE, related_name='dentist_appointments', to=settings.AUTH_USER_MODEL)),
                ('procedures', models.ManyToManyField(to='booking.procedure')),
            ],
        ),
    ]
