# Generated by Django 4.0.5 on 2022-06-26 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='start_time',
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('occupied', 'Occupied')], default='pending', max_length=64)),
                ('start_time', models.DateTimeField()),
                ('dentist', models.ForeignKey(limit_choices_to=models.Q(('groups__name', 'Doctors')), on_delete=django.db.models.deletion.CASCADE, related_name='dentist_schedules', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='schedule',
            field=models.OneToOneField(default=None, limit_choices_to=models.Q(('status', 'pending')), on_delete=django.db.models.deletion.CASCADE, related_name='schedule_appointment', to='booking.schedule'),
        ),
    ]
